### ISSUE TITLE
Change to better bundler 

### ISSUE THREAD

**Issue by konhi** [cloudflare/worker-typescript-template#62]
I suggest changing the default bundler from webpack to something different, such as [esbuild](https://github.com/evanw/esbuild) or [swc](https://github.com/swc-project/swc). I moved to esbuild, and instantly noticed
- surprising build times while developing with `wrangler dev` 🥰
- support for Module Workers (webpack doesn't seem to support for `export`, correct me if I'm wrong) - Cloudflare advises to use it, as it gives [few advantages](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/#advantages-of-migrating) including support for Durable Objects

Example template is shown there: https://github.com/codewithkristian/esbuild-typescript-modules-workers-template

**Comment by JacobMGEvans** [comment]
This example is now using Wrangler2 and has it as a dependency which utilizes ESBuild currently.
