### ISSUE TITLE
Can not use native node modules

### ISSUE THREAD

**Issue by pjain11** [cloudflare/worker-typescript-template#66]
I'm trying to use performance api. 
In handler.ts I added - 
 import { performance } from "perf_hooks"; 
And trying to do performance.now()

I've @types/node added as dev dependency and it is also present in tsconfig.

I get this error 'Can't resolve 'perf_hooks'. (I'm using Node 16.x and i see that this module is present in node_modules/@types/node folder)

Any thoughts how to resolve this?

**Comment by andrekutianski** [comment]
Same issue here

**Comment by JacobMGEvans** [comment]
If you are using Wrangler2 recent versions, try running your Worker with flag `--node-compat`
